Csharp/netcore/the_wall/Models/DbModels/BaseEntity.cs
namespace the_wall.Models{
    public abstract class BaseEntity{}
}

Csharp/netcore/the_wall/Models/DbModels/Comment.cs
using System;

namespace the_wall.Models{
    public class Comment : BaseEntity{
        public int Id{ get;set; }
        public int UserId{ get;set; }
        public int MessageId{ get;set; }
        public string Content{ get;set; }
        public DateTime CreatedAt{ get;set; }
        public DateTime UpdatedAt{ get;set; }
    }
}

Csharp/netcore/the_wall/Models/DbModels/Message.cs
using System;

namespace the_wall.Models{
    public class Message : BaseEntity{
        public int Id{ get;set; }
        public int UserId{ get;set; }
        public string Content{ get;set; }
        public DateTime CreatedAt{ get;set; }
        public DateTime UpdatedAt{ get;set; }
    }
}

Csharp/netcore/the_wall/Models/DbModels/User.cs
using System;

namespace the_wall.Models{
    public class User : BaseEntity {
        public int Id{ get;set; }
        public string FirstName{ get; set; }
        public string LastName{ get;set; }
        public string Email{ get;set; }
        public string Password{ get;set; }
        public string PasswordConfirmation{ get;set; }
        public DateTime CreatedAt{ get;set; }
        public DateTime UpdatedAt{ get;set; }
    }
}

Csharp/netcore/the_wall/Models/ErrorViewModel.cs
using System;

namespace the_wall.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Csharp/netcore/the_wall/Models/VIewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace the_wall.Models {
    public class Login : BaseEntity{
        [Required]
        [EmailAddress]
        public string EmailLog{ get;set; }
        [Required]
        [DataType(DataType.Password)]
        public string PasswordLog{ get;set; }
    }
}

Csharp/netcore/the_wall/Controllers/WallController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace the_wall.Controllers{
    public class WallController : Controller{
        [HttpGet]
        [Route("")]
        public IActionResult Index(){
            return View();
        }
    }
}

Csharp/netcore/the_wall/Views/Wall/LoginPartial.cshtml
@model the_wall.Models.Login

<form asp-controller="Wall" asp-action="login" method="post">
    <span>@ViewBag.LoginError</span>
    <table>
    <tr>
        <td><label for="EmailLog">Email Address</label></td>
        <td><input type="text" name="EmailLog" id="EmailLog">
        <span asp-validation-for="EmailLog"></span></td>
    </tr>
    <tr>
        <td><label for="PasswordLog">Password</label></td>
        <td><input type="text" name="PasswordLog" id="PasswordLog">
        <span asp-validation-for="PasswordLog"></span></td>
    </tr>
    <tr>
        <td></td>
        <td><input type="submit" class="btn btn-default" value="Sign in">
    </tr>
</table>
</form> 

Csharp/netcore/the_wall/Views/Wall/index.cshtml
<link rel="stylesheet" href="~/css/index.css">
@model the_wall.Models.User

<h1>Register</h1>
<form asp-controller="Logreg" asp-action="Register" method="POST">
    <table>
        <tr>
            <td><label asp-for="FirstName"></label></td>
            <td><input asp-for="FirstName">
            <span asp-validation-for="FirstName"></span></td>
        </tr>
        <tr>
            <td><label asp-for="LastName"></label></td>
            <td><input asp-for="LastName">
            <span asp-validation-for="LastName"></span></td>
        </tr>
        <tr>
            <td><label asp-for="Email"></label></td>
            <td><input asp-for="Email">
            <span asp-validation-for="Email"></span></td>
        </tr>
        <tr>
            <td><label asp-for="Password"></label></td>
            <td><input asp-for="Password">
            <span asp-validation-for="Password"></span></td>
        </tr>
        <tr>
            <td><label asp-for="PasswordConfirmation"></label></td>
            <td><input asp-for="PasswordConfirmation">
            <span asp-validation-for="PasswordConfirmation"></span></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" class="btn btn-default" value="Register"></td>
        </tr>
    </table>
</form>
<h1>Sign in</h1>
@Html.Partial("LoginPartial")